name: CI - Simple

# Trigger on push to main/master or pull requests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Test and build
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Step 2: Set up Go
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    
    # Step 3: Run tests
    - name: Run tests
      run: |
        go test -v ./crawler
        go test -cover ./crawler
    
    # Step 4: Build binary
    - name: Build
      run: go build -v .
    
    # Step 5: Build Docker image
    - name: Build Docker image
      run: docker build -t web-crawler:latest .
    
    # Step 6: Test Docker image
    - name: Test Docker image
      run: docker run --rm web-crawler:latest --help